### PR TITLE
corrected LED part no.

### PR DESCRIPTION
**Pull request by DaneEvans**
corrected LED part no. in the RGBbuild guide, now sk6812-mini

### CODE REVIEW

**Review by josefadamcik — APPROVED** [review]
Thanks for a quick fix!

**Comment by DaneEvans** [comment]
no worries, I've added 'issues' to my notifications so I still see them if
I don't get @'d

**Comment by fi0** [comment]
Is this different from crkbd v3's sk6812mini-e?

**Comment by DaneEvans** [comment]
> Is this different from crkbd v3's sk6812mini-e?

They are different, although those look like they may fix some of the soldering issues. I wish I'd seen them earlier

**Pull request merged**
