### PR TITLE
Sofle Choc variant

### LINKED ISSUE #40: v2 Choc RGB variant
keyboard

keyboard_side

I am working on variant that supports Kailh choc switches, hotswap sockets and per-key RGB. Based on @DaneEvans's Sofle RGB (thanks).

Pull Request:
https://github.com/josefadamcik/SofleKeyboard/pull/104

Welcome feedback and/or collaboration with anyone interested.

#### TODO
- [x] Verify hardware
  - [x] switches
  - [x] OLED
  - [x] LEDs
  - [x] encoders
  - [x] split
- [x] Firmware
  - [x] basic setup
  - [x] split config
  - [x] keymap
  - [x] LED config
  - [x] LED physical positions
  - [x] cleanup
- [x] PCB v2.1
  - [x] fix traces too close to pads
  - [x] bump version to 2.1
  - [x] better led orientation marks
  - [x] change all markings to silkscreen
  - [x] vertically enlarge encoder cutout on top plate
  - [x] regenerate gerbers
- [x] build guide
  - [x] controller orientation
  - [x] LED orientation, order, soldering tips
  - [x] BOM - no spacers needed
  - [x] top plate is not compatible with original/rgb
  - [x] photos
  - [x] firmware
- [ ] publish 
  - [x] PR to this repo
  - [ ] PR for qmk firmware

### PR DESCRIPTION
**Pull request by brianlow**
SofleChoc_1
keyboard_side

The Sofle Choc is a variation of the Sofle with:

   - low-profile, Kailh Choc switches
   - hotswap sockets
   - per-key RGB
   - thin, 15mm from desktop to top of keycaps
   - Sofle v2 switch layout with the more aggressive pinky stagger

I've built the v2.0 version and use it daily. This PR is a v2.1 version with a few minor fixes/tweaks but I have not built it. v.2.1 has been built by a few poeple so far.

Can preview the build guide in this PR here:
https://github.com/josefadamcik/SofleKeyboard/blob/27579fdc7e9a97dca35b73e7a9bfa7a9111230ac/docs/build_guide_choc.md

Closes #40

### CODE REVIEW

**Comment by josefadamcik** [comment]
Thanks a lot for the contribution! It might take some time for me to review the design, feel free to remind me if it was taking too long.

**Comment by brianlow** [comment]
@josefadamcik sounds good, let me know if there is anything I can do to make review easier

**Comment by ebnewt** [comment]
How do you like the 19.1 vertical spacing for the choc keycaps? I'm designing an offshoot of the Sofle for chocs with an extra column and nav keys. I'm debating 19.1 vs 17mm or somewhere in-between.  Also, how is the top plate fit with 14mm?  Have you ever tried 13.8?

**Comment by brianlow** [comment]
@ebnewt 

> How do you like the 19.1 vertical spacing for the choc keycaps?

Works for me. I don't think I want a tighter key spacing for my hand size. Though not sure how much difference Choc spacing would make. Might look nicer when using opaque keycaps. 

> how is the top plate fit with 14mm? Have you ever tried 13.8?

Switches are held firm but not super tight. I sometimes pull the switch out when taking a keycap off. I think worth trying 13.8mm.

**Comment by dweisiger** [comment]
@brianlow first of all thanks for all the work in this - its really awesome. second, i believe this pinky stagger is the same as the sofle v1, which is similar to the corne/lily, is that correct? if so, are there any plans to make a version of this with a more aggressive pinky stagger such as in the v2? if not i might give it a shot myself.

**Comment by brianlow** [comment]
This is based off the Sofle RGB which I am pretty sure is based ok Sofle v2 which had the more aggressive stagger. Not at a computer to confirm though. 

In any case, I don't have any plans for further revisions. Feel free to ask if you try modifying.

**Comment by dweisiger** [comment]
@brianlow i figured it out - yes the sofle RGB is based on the sofle V2, but it makes a few small modifications mainly the plate is different shaped a bit and then also the pinky stagger is less aggressive. Thanks for the info! I think I'll roll with this one anyways..and if I really want that aggressive stagger I'll have to learn kicad lol.

**Comment by brianlow** [comment]
@Ataraxis7 replying here in case others find useful

> i just wanted to relay that it looks like the pinky stagger may be the less aggressive iteration. It was reduced back to ~V1 stagger in the "RGB" (though thumb key placements remained V2 layout) to about 1/3 a key lower instead of about 2/3


Thanks for confirming. I didn't look too closely earlier. Will update the PR

> i see the recent update/comment for V2.1 gerber files, but the files themselves are still labeled "Gerbers/Choc_v2/choc-v2-gerber-pcb.zip". I wasn't sure based on your comments in the guide so wondered if i may inquire if these reflect your V2.1 tweaks or those are not yet uploaded?

The gerbers on this branch should have all the v2.1 changed. I should have renamed the files. You can confirm this by checking the encoder opening on the top plate. It will be vertically 1mm larger on v2.1 vs v2.0. See the commit log for other v2.1 changes (all pretty minor). 

Hope that helps

**Comment by frankbaumgarten** [comment]
Just a comment about your 2.1 gerber files because jlc came back to me..... its missing the drill files

**Comment by brianlow** [comment]
@frankbaumgarten thanks! Zips updated with drill files. Sorry it took so long. If you do build it, I would love to hear how it went

**Comment by marcjmiller** [comment]
> I did too. $15.20 CAD on 5 boards. Wasn't sure if there was a way to avoid this charge.

Same here, but USD; At least it wasn't just me.

**Comment by frankbaumgarten** [comment]
Strange, got 10 pcbs and 10 switch plates from jlcpcb without them complaining about to narrow areas and charging more. Maybe the trick is to leave out the drill files so they ask you to change the files and dont check the new ones that much ;)

**Comment by brianlow** [comment]
Learned you can preview the build guide without compiling it:
https://github.com/josefadamcik/SofleKeyboard/blob/648a410e2aaf8b093cedc35099cd9fa48d592c35/docs/build_guide_choc.md

cc @blewisemt

**Comment by josefadamcik** [comment]
@brianlow and all.
Sorry for the delay on this, last month was very busy (moving to new city). I am going to check the PR briefly now and merge it. I have been paying attention to the discussions here and here https://github.com/josefadamcik/SofleKeyboard/issues/40 and I do believe it's ready.

**Comment by josefadamcik** [comment]
@brianlow I must thank you again for high quality PR and for the time you took with the build guide etc. Awesome. I am merging it with this comment.

**Comment by brianlow** [comment]
Thank you!

**Pull request merged**
