### PR TITLE
plates in svg format for laser cutting(rgb version)

### PR DESCRIPTION
**Pull request by kissetfall**

### CODE REVIEW

**Comment by kissetfall** [comment]
resolves #96

**Comment by kissetfall** [comment]
resolves josefadamcik/SofleKeyboard#78

**Comment by kissetfall** [comment]
Also added for the standard sofle v2

**Comment by josefadamcik** [comment]
@kissetfall Thanks a lot for the contribution! 

Have you already had those made? Or are you going to?

**Comment by kissetfall** [comment]
@josefadamcik 
> Have you already had those made? 

Yep, both works great.

**Pull request merged**
