### PR TITLE
include 3D printable case(v1)

### PR DESCRIPTION
**Pull request by Canorus**
I was asked to share my 3D printable sofle keyboard case on IG. When I decided to share my model, I realized v2 was launched and not compatible with v1. Since my model is based on v1, I can understand if you reject this pr.

STL files and gcode files are under /Sofle_v1/Case/3D Print/

### CODE REVIEW

**Review by josefadamcik — CHANGES_REQUESTED** [review]
Sorry for not reviewing this earlier. 

I am not sure if I understand the PR actually. You said you are submitting a 3D printed case, but there are only STL and GCODE files for the palm rests. I don't think they are interesting on their own.

Perhaps you forgot to commit the design of the actually case?

Also, remove the gcode files please. They are specific to 3d printer / slicer and they are no use when people don't know what is your printer and settings for generating them. In general people would slice the print themselves anyway.

**Comment by Canorus** [comment]
I am so sorry for wasting your time. I removed .gcode files and added missing actual case .stl files.

While I was exporting the 3d model, I realized that the case was designed to fit modified version of SofleKeyboard that replaced TRRS connector to USB4085 receptacle instead of the original SofleKeyboard. Not that it will block the TRRS cable or anything but it may look awkward in a way. I'll try to update the design when I can.

**Comment by josefadamcik** [comment]
@Canorus 
> I am so sorry for wasting your time. I removed .gcode files and added missing actual case .stl files.

Thanks and don't worry :)

>  I realized that the case was designed to fit modified version of SofleKeyboard that replaced TRRS connector to USB4085 receptacle instead of the original SofleKeyboard. Not that it will block the TRRS cable or anything but it may look awkward in a way. I'll try to update the design when I can.

I think it would be better if it was adjusted for the original design if it's going to be in the main repository. If you adjust the case, I'll accept the PR.


That said, you don't have to do any modification if you don't want.  I think it would be perfectly fine to put the STL files in Thingiverse or similar, put some description to it and people will find it when they search for "sofle case". There are few 3d printed cases there already and there is no big need to have the case in the main repository.

**Comment by Canorus** [comment]
> I think it would be better if it was adjusted for the original design if it's going to be in the main repository.

That was what I was thinking. I managed to find some time to make the adjustment and fortunately there wasn't much to be done. Now the case fits to original design.

> I think it would be perfectly fine to put the STL files in Thingiverse or similar, put some description to it and people will find it when they search for "sofle case". 

I thought about that too, but then I would have to include modified pcb too. I thought it'd be better just to contribute to the original repo if that's the case.

Anyway, I was glad I could contribute. Sofle Keyboard was my first split keyboard and first custom-ish keyboard. Please check when it's convenient for you.

**Pull request merged**
